# Generated by Django 2.2 on 2019-07-31 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='URL',
            new_name='shortURLgen',
        ),
    ]
