# Generated by Django 2.2 on 2019-07-31 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_auto_20190730_1816'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shortURLgen',
            new_name='shortened_url',
        ),
    ]
