# Generated by Django 2.2 on 2019-07-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0003_auto_20190730_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortened_url',
            name='code',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
