# Generated by Django 2.1.5 on 2019-04-22 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='eye_color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contacts.EyeColor'),
            preserve_default=False,
        ),
    ]
