# Generated by Django 2.1.5 on 2019-04-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20190422_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='eye_color',
        ),
        migrations.AddField(
            model_name='contact',
            name='eye_color',
            field=models.ManyToManyField(to='contacts.EyeColor'),
        ),
    ]
