# Generated by Django 2.2.3 on 2019-07-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('birthday', models.DateField(verbose_name='birthday')),
                ('phone_number', models.CharField(max_length=200)),
                ('is_cell', models.BooleanField()),
            ],
        ),
    ]
