# Generated by Django 2.1.5 on 2019-05-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AjaxDemoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('favorite_animal', models.CharField(max_length=200)),
                ('hot_or_not', models.BooleanField()),
            ],
        ),
    ]
